#!/bin/sh
systemctl stop cowrie.service
sleep 10
# delete small logs (likely irrelevant) and logs older then a week
find /srv/cowrie/log/tty/ -size -1000c -name '*.log' -delete
find /srv/cowrie/var/lib/cowrie/tty/ -size -1000c -name '*.log' -delete
find /srv/cowrie/log/tty/ -ctime +7 -name '*.log' -delete
find /srv/cowrie/var/lib/cowrie/tty/ -ctime +7 -name '*.log' -delete
find /srv/cowrie/log -name 'cowrie.log.*' -ctime +7 -delete
find /srv/cowrie/log -name 'cowrie.json.*' -ctime +7 -delete
find /srv/cowrie/var/log/cowrie -name 'cowrie.log.*' -ctime +7 -delete
find /srv/cowrie/var/log/cowrie -name 'cowrie.json.*' -ctime +7 -delete
systemctl start cowrie.service

