#!/bin/sh

####
#
#  hourly checking with dshield. to be expanded for update check
#
####

version=0.0
. /etc/dshield.conf
nonce=`openssl rand -hex 10`
hash=`echo -n $email:$apikey | openssl dgst -hmac $nonce -sha512 -hex | cut -f2 -d'=' | tr -d ' '`
user=`echo $email | sed 's/@/%40/'`
newversion=`wget -q -O - https://isc.sans.edu/api/checkapikey/$user/$nonce/$hash | grep '<result>ok</result>' | grep '\<version\>' | sed 's/.*<version>//' | sed 's/<\/version>.*//'`
majornewversion=`echo $newversion | cut -f1 -d'.'`
majoroldversion=`echo $version | cut -f1 -d'.'`
minornewversion=`echo $newversion | cut -f2 -d'.'`
minoroldversion=`echo $version | cut -f2 -d'.'`
if [ "$majoroldversion" -lt "$majornewversion" ]; then
    echo "UPDATE"
    git -C $progdir pull -q
    $progdir/update.sh
    exit
fi
if [ $majoroldversion -eq $majornewversion ]; then
  if [ $minoroldversion -lt $minornewversion ]; then
      echo "UPDATE"
      git -C $progdir  pull -q
      $progdir/update.sh
      exit
  fi
fi
echo "NO UPDATE"
