template(name="json_output" type="list" option.jsonf="on") {
    property(outname="timestamp" name="timereported" dateFormat="rfc3339" format="jsonf")
    property(outname="host" name="hostname" format="jsonf")
    property(outname="message" name="msg" format="jsonf")
}

$template DShieldTemplate,"%timegenerated:::date-unixtimestamp% %HOSTNAME% %syslogtag%%msg%\n"
if $msg contains " DSHIELDINPUT " then /var/log/dshield.log;DShieldTemplate
& stop
