name: ISC Agent Code Check Action

on:
  pull_request:
    branches: [ISC-1-isc-agent-beta]

jobs:
  code-check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Code scan
      run: make ops-scan
      working-directory: ./srv/isc-agent
