name: ISC Agent Code Check Action

on:
  pull_request:
    branches: [epic/ISC-1-web-rebuild]

jobs:
  code-check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Code scan
      run: make ops-scan
      working-directory: ./srv/isc-agent
