name: ISC Agent Code Check Action

on:
  pull_request:
    branches: [develop, development, master, main, stage]

jobs:
  code-check:
    name: Code Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Code scan
      run: make ops-scan
      working-directory: ./srv/isc-agent
