name: Snyk Static Application Security Testing

on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - run:
        cd ../..
    - name: Snyk test
      run: snyk test --all-projects --detection-depth=10
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}