name: Snyk Static Application Security Testing

on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: snyk/actions/setup@master
    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - run:
        pip install -r bin/requirements.txt
    - name: Snyk test
      run: snyk test --all-projects --detection-depth=10 --skip-unresolved --sarif-file-output=snyk.sarif
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
    - name: Upload result to GitHub Code Scanning
      if: always()
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: snyk.sarif